# Base image
FROM gcc:13.2 as builder

# Copy all files to root directory
COPY . /

# Compile the C application using Makefile
RUN make

# Final image
FROM scratch
COPY --from=builder /compiled-app /compiled-app
CMD ["./compiled-app"]
