FROM eclipse-temurin:21-jdk as builder

WORKDIR /app
COPY ./app /app/

RUN apt-get update && apt-get install -y maven  && \
    mvn package

FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY --from=builder /app/target/app.jar /app/

CMD ["java", "-jar", "/app/app.jar"]